package KieRule;
import com.gigatorb.springbootdrools.model.Order;
import com.gigatorb.springbootdrools.model.Shipping;


rule "HDFC"

when
    orderObject: Order(cardType=="HDFC" && price>10000);
then
    orderObject.setDiscount(10);
end;

rule "ICICI"

when
    orderObject : Order(cardType=="ICICI" && price>15000);
then
    orderObject.setDiscount(8);
end;

rule "DBS"

when
    orderObject : Order(cardType=="DBS" && price>15000);
then
    orderObject.setDiscount(15);
end;


rule "GROSS-TONNAGE"

when
    shippingObject: Shipping($gt: gt, $ratePOS: ratePOS);
		
then
    System.out.println("Gross Tonnage : " + ($gt /100)*$ratePOS);
    shippingObject.setTotalGT(($gt /100)*$ratePOS);
end;

